services:
  api:
    container_name: api
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_URL=jdbc:postgresql://postgres:5432/bu-credito
      - TOKEN_SECRET=root
    ports:
      - 8080:8080
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bu-credito'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
