spring:
    application:
        name: desafio-celcoin
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        show-sql: false
server:
    error:
        include-stacktrace: never
springdoc:
    swagger-ui:
        path: /
token:
    secret: ${TOKEN_SECRET}